### ISSUE TITLE
Please use meaningful name instead of RtMidi.... for MIDI inputs/outputs

### ISSUE THREAD

**Issue by mark-orion** [wolfschus/sequencegang5#10]
I am trying to get sequencegang5 to run on my Pi4 with PatchboxOS. The problem is that the generic name of the MIDI in- and outputs collides with Patchbox that uses RtMidi as well. This makes MIDI routing difficult. It would be great if Sequencegang5 would identify itself with a meaningful name to ALSA.

**Comment by wolfschus** [comment]
Hi Mark,
I have to redesign the handling of the MIDI-Events.
At the moment, it is quick and dirty. I open a MIDI-Device before I send MIDI Data and close it after.

**Comment by wolfschus** [comment]
Has been revised, names of the instruments are displayed.
