### ISSUE TITLE
Missing dependency and wrong filenames in README.md and docs

### ISSUE THREAD

**Issue by mark-orion** [wolfschus/sequencegang5#9]
This is a great project! The first sequencer that works fine on a Raspi with Touchscreen. Thanks a lot!

I just tried to install it on my Pi4 following the instructions and I discovered some errors with the filenames:
- db/sequencegang5.settings has a typo in the filename
- the hidden file has to be called ~/.sequencegang5.settings and not .sequencegang.settings
- wiringpi has to be installed (missing dependency on RasPi).

It would be great to have a screenshot or a short video demonstrating the software so that people know what to expect before taking the effort to compile / install.

**Comment by wolfschus** [comment]
Thank you very much for the info. Is fixed.
I am working on a documentation, but this takes sometimes more time than programming ;-)
